parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     albert
    database_user:     hofmann
    database_password: bicycle1943

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~
    mailer_delivery:   me@example.com
    mailer_from:       me@example.com
    mailer_sender:     me@example.com

    payments_secret:  som3S3cr37P4ssw0rd
    mtgox_api_key:    apiKey
    mtgox_api_secret: "apiSecret"

    ads_default_currency: EUR
    page_title: "acid.name.long"

    locale:            pl
    secret:            0724ebb222af8866b7d7a2524451219b

    session_memcache_host: 127.0.0.1
    session_memcache_port: 11211
    session_memcache_prefix: "acid_"
    session_memcache_expire: 3600

    application_memcache_host: 127.0.0.1
    application_memcache_port: 11211
    application_memcache_prefix: "acid_"

    max_one_banner_days: 365
    announcement_expire_days: 10 # if announcement is not edited for {announcement_expire_days}, it will be marked as expired by acid:task:expire-announcements
    announcement_edit_cost: 0.01
    announcement_edit_currency: PLN

    payment_hash_algorithm: sha224
    payment_hash_key: sAf3HaShK3Y

    bitpay_api_key: sAf3Ap1K3Y
    bitpay_transaction_speed: medium
    bitpay_full_notifications: false #if true bitpay will inform about every status change
    bitpay_notifications_email: name@example.com

    # currently valid value is "omnipay_bitpay" only
    banner_payment_methods:
        - omnipay_bitpay

    announcement_payment_methods: ~

    announcement_flow_mail_recipients:
        - "mail@example.com"
        - "another-mail@example.com"